version: '3.8'

services:
  backend:
    build: ./fullstack_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./energy-frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend